name: Node CI

on: 
  push:
    paths: whatabyte-portal/**

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        path: whatabyte-portal
    - name: npm install, build        
      run: |
        npm run build --if-present
      env:
        GITHUB_WORKSPACE: whatabyte-portal
